repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the revision or tag you want to pin to
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=500']  # Replace '500' with the size limit you prefer, in KB

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the revision or tag you want to pin to
    hooks:
      - id: black
        language_version: python3  # Specify the Python version black should use
