deepspeed train/pipeline7b.py \
    --x_col "headline" \
    --exp_name "llama7B test_saving" \
    --y_col "RET_10D_pos" \
    --filename_headlines  "news_headlines_v3.2.parquet" \
    --output_dir "results/Llama_SFT" \
    --lora_dim "2" \
    --bf16 \
    --model_name  "mistralai/Mistral-7B-v0.1" \
    --per_device_train_batch_size "4" \
    --per_device_eval_batch_size "4" \
    --pooler_type_logits "last" \
    --save_total_limit "1" \
    --learning_rate "0.00001" \
    --weight_decay "0.005" \
    --num_labels "2" \
    --gradient_accumulation_steps "5" \
    --evaluation_strategy "epoch" \
    --num_train_epochs "1" \
    --remove_unused_columns False \
    --push_to_hub True \
    --is_debug \
    --deepspeed deepspeed_confs/ds_config_zero2_v1.json
